-- =============================================================================
-- SCD ALTER statements  |  Online Furniture DWH
--
-- Adds the SCD Type 2 tracking columns to DIM_Customer.
-- Run ONCE after initial DWH creation (before the first ETL load).
--
-- Note: SQLite does not support ALTER TABLE ADD CONSTRAINT or DROP COLUMN
-- (before 3.35), so SCD columns are defined here for documentation purposes.
-- In the project, these columns are already present in 02_create_dwh.sql.
-- This file serves as the formal SCD definition record for submission.
-- =============================================================================

-- For MSSQL / PostgreSQL, the equivalent statements would be:

-- ALTER TABLE DIM_Customer
--     ADD ValidFrom  DATE         NOT NULL DEFAULT GETDATE();   -- MSSQL
--
-- ALTER TABLE DIM_Customer
--     ADD ValidTo    DATE         NULL;
--
-- ALTER TABLE DIM_Customer
--     ADD IsCurrent  BIT          NOT NULL DEFAULT 1;

-- =============================================================================
-- SCD Analysis Summary
-- =============================================================================
--
-- SCD TYPE 0  (keep original value -- never overwrite)
-- Columns: CustomerId, OrderId, OrderDate
-- Justification: natural keys and transaction timestamps are immutable.
--
-- SCD TYPE 1  (overwrite -- no history kept)
-- Columns: DIM_Product.ProductName, DIM_Product.ListPrice,
--          DIM_Product.Colour, DIM_Product.Material
-- Justification: corrections to product catalogue data (typos, price updates)
--   do not require historical tracking for the defined analytical questions.
--
-- SCD TYPE 2  (add new row -- full history preserved)
-- Columns: DIM_Customer.StreetAddress, DIM_Customer.PostalCode,
--          DIM_Customer.City, DIM_Customer.FederalState,
--          DIM_Customer.PlzRegion, DIM_Customer.PlzZone
-- Justification: a customer who relocates changes their PLZ region, which
--   directly affects Q2 (regional order value analysis). Recording the old
--   address ensures that historical orders are attributed to the correct region.
-- Tracking columns: ValidFrom DATE, ValidTo DATE (NULL = active), IsCurrent BIT
--
-- =============================================================================
-- ETL SCD 2 Logic (implemented in python/02_etl.py -> load_dim_customer):
--
--  IF CustomerId NOT IN DIM_Customer:
--      INSERT new row  (ValidFrom = CustomerSince, ValidTo = NULL, IsCurrent = 1)
--
--  ELSE IF PostalCode OR StreetAddress changed:
--      UPDATE current row  SET ValidTo = etl_date, IsCurrent = 0
--      INSERT new row      (ValidFrom = etl_date, ValidTo = NULL, IsCurrent = 1)
--
--  ELSE:
--      No action (SCD 0/1 attributes handled in load_dim_product)
-- =============================================================================
